#!/usr/bin/env node

import { mkdirSync, writeFileSync, existsSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { execSync } from 'node:child_process';
import { randomBytes } from 'node:crypto';

const args = process.argv.slice(2);
const projectName = args[0];

if (!projectName) {
  console.error('Usage: npx create-htmless <project-name>');
  console.error('');
  console.error('Example:');
  console.error('  npx create-htmless my-cms');
  process.exit(1);
}

const projectDir = resolve(process.cwd(), projectName);

if (existsSync(projectDir)) {
  console.error(`Error: Directory "${projectName}" already exists.`);
  process.exit(1);
}

console.log(`\nCreating HTMLess project in ${projectDir}...\n`);

mkdirSync(projectDir, { recursive: true });

// ─── Generate secrets ───

const jwtSecret = randomBytes(32).toString('hex');
const dbPassword = randomBytes(16).toString('hex');

// ─── docker-compose.yml ───

const dockerCompose = `## HTMLess CMS
## Start: docker compose up -d
## Admin: http://localhost:3001
## API:   http://localhost:3000

services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: htmless
      POSTGRES_PASSWORD: \${DB_PASSWORD}
      POSTGRES_DB: htmless
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U htmless"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    image: htmless/api:latest
    restart: unless-stopped
    ports:
      - "\${API_PORT:-3000}:3000"
    environment:
      DATABASE_URL: postgresql://htmless:\${DB_PASSWORD}@postgres:5432/htmless
      REDIS_URL: redis://redis:6379
      JWT_SECRET: \${JWT_SECRET}
      PORT: "3000"
      NODE_ENV: production
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  worker:
    image: htmless/worker:latest
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://htmless:\${DB_PASSWORD}@postgres:5432/htmless
      REDIS_URL: redis://redis:6379
      NODE_ENV: production
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  admin:
    image: htmless/admin:latest
    restart: unless-stopped
    ports:
      - "\${ADMIN_PORT:-3001}:3001"
    environment:
      NODE_ENV: production
    depends_on:
      - api

volumes:
  pgdata:
  redisdata:
`;

// ─── .env ───

const envFile = `# HTMLess Environment Configuration
# Generated by create-htmless

# Database
DB_PASSWORD=${dbPassword}

# Auth
JWT_SECRET=${jwtSecret}

# Ports (optional)
API_PORT=3000
ADMIN_PORT=3001
`;

// ─── .gitignore ───

const gitignore = `node_modules/
dist/
.env
.env.local
.env.production
*.log
.DS_Store
`;

// ─── package.json ───

const packageJson = {
  name: projectName,
  version: '0.1.0',
  private: true,
  description: `${projectName} — powered by HTMLess CMS`,
  scripts: {
    start: 'docker compose up -d',
    stop: 'docker compose down',
    logs: 'docker compose logs -f',
    'db:seed': 'docker compose exec api node packages/core/dist/cli/index.js seed',
  },
};

// ─── Write files ───

writeFileSync(join(projectDir, 'docker-compose.yml'), dockerCompose);
writeFileSync(join(projectDir, '.env'), envFile);
writeFileSync(join(projectDir, '.gitignore'), gitignore);
writeFileSync(join(projectDir, 'package.json'), JSON.stringify(packageJson, null, 2) + '\n');

// ─── Initialize git ───

try {
  execSync('git init', { cwd: projectDir, stdio: 'pipe' });
} catch {
  // git not available, skip
}

// ─── Detect package manager and install ───

const userAgent = process.env.npm_config_user_agent || '';

let pm = 'npm';
if (userAgent.startsWith('pnpm')) {
  pm = 'pnpm';
} else if (userAgent.startsWith('yarn')) {
  pm = 'yarn';
} else if (userAgent.startsWith('bun')) {
  pm = 'bun';
}

// ─── Done ───

console.log('Your HTMLess CMS is ready!\n');
console.log('Next steps:\n');
console.log(`  cd ${projectName}`);
console.log('  docker compose up -d\n');
console.log('Once running:\n');
console.log('  Admin UI:  http://localhost:3001');
console.log('  API:       http://localhost:3000');
console.log('  Login:     admin@htmless.com / admin123\n');
console.log('After first boot, run the database seed:');
console.log('  docker compose exec api pnpm --filter @htmless/core prisma db push');
console.log('  docker compose exec api pnpm --filter @htmless/core prisma db seed\n');
console.log('Docs: https://htmless.com');
console.log('GitHub: https://github.com/HTMLess-CMS/HTMLess\n');
